### ISSUE TITLE
Reject not defined crash bug

### ISSUE THREAD

**Issue by moueza** [moueza/4668271-developpez-des-applications-web-avec-angular#21]
Console when Tout allumer button pressed :
` localhost/:1 Error handling response: ReferenceError: reject is not defined
    at n (chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/content.js:24:4080)
    at chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/content.js:24:4221`

**Comment by moueza** [comment]
by string constraint removal

**Comment by moueza** [comment]
Still occurs
